### ISSUE TITLE
Per NDIS Connection Offload Status

### ISSUE THREAD

**Issue by nibanks** [microsoft/quic-offloads#26]
In the NDIS section about offloading connections ([link](https://github.com/microsoft/quic-offloads/blob/main/quic-encryption-offload.md#establishing-encryption-parameters-for-a-connection-1)) we mention it's an array of connections to be added/removed, but I think we need an output parameter, per connection, to indicate if that operation succeeded or failed. For instance, what if we add 2 connections, but the HW only has memory available for 1? Should the whole operation fail, or just the second add?

**Comment by BorisPis** [comment]
Makes sense to me
