### ISSUE TITLE
Support HW URO

### ISSUE THREAD

**Issue by nibanks** [microsoft/quic-offloads#35]
Along with QEO, we should most likely support HW URO. This topic was brought up in #30, but I think it is worth a separate issue.

**Comment by nibanks** [comment]
Just pushed an empty doc to start filling in for this [here](https://github.com/microsoft/quic-offloads/blob/main/udp-reassembly-offload.md).

**Comment by anrossi** [comment]
@stevedoyle, @BorisPis
We've got a URO spec written at the above link, but I'd like to direct your attention to the [NDIS Rules](https://github.com/microsoft/quic-offloads/blob/main/udp-rsc-offload.md#rules) section of the document.
Specifically, is the hardware capable of coalescing just the UDP payloads, provided all the other conditions are met?  Any other questions or comments on this document are welcome.

**Comment by nibanks** [comment]
I'm going to resolve this issue since we now have the URO spec written up. Folks please provide any specific feedback you might have in new GitHub issues.
